export const UPDATE_PRO_BY_ID = 'UPDATE_PRO_BY_ID';
export const FILTER_BY_NAME = 'FILTER_BY_NAME';
export const FILTER_BY_DATE = 'FILTER_BY_DATE';
export const PRODUCT_FILTER_SCREEN_VISIBLE = 'PRODUCT_FILTER_SCREEN_VISIBLE';
